function(simplecv_add_test name)
  add_executable(${name} ${name}.cpp)
  target_link_libraries(${name} PRIVATE SimpleCV::simplecv)
  target_compile_features(${name} PRIVATE cxx_std_17)
  add_test(NAME ${name} COMMAND ${name})
endfunction()

simplecv_add_test(test_simplecv)
simplecv_add_test(test_draw)
simplecv_add_test(test_warp)
simplecv_add_test(test_proc)
simplecv_add_test(test_utils)
simplecv_add_test(test_text)
